### PR TITLE
Migrating ELT docs

### PR DESCRIPTION
**Pull request by fabianriewe**

### CODE REVIEW

**Comment by cgkournelos-rf** [comment]
@fabianriewe can you check if I have "write access" to this repo?
I trying to push a commit with some changes and it fails/

**Comment by fabianriewe** [comment]
@cgkournelos-rf it says that your invite is still pending 🤔

**Review by fabianriewe — COMMENTED** [review]
LGTM

**Comment by cgkournelos-rf** [comment]
Perfect, you updated also the links to airbyte!

**Comment by cgkournelos-rf** [comment]
I am not sure why these checks are failing

**Comment by fabianriewe** [comment]
There was just some linting going wrong

**Pull request merged**
