### PR TITLE
Update registry.md

### PR DESCRIPTION
**Pull request by Lefey**
typo

### CODE REVIEW

**Comment by fabianriewe** [comment]
Thank you for your contribution 🚀  Feel free to send your KYVE address here so we can give you some Korellia points.

**Comment by Lefey** [comment]
> 

kyve1fqlwm2xc7a9l5fcfnn8k65q8vcpgxnl5mk8yd9

**Comment by Lefey** [comment]
@fabianriewe I would be very glad to get some points ) but I don't understand in which section of Korellia profile to expect them?
My KYVE address kyve1fqlwm2xc7a9l5fcfnn8k65q8vcpgxnl5mk8yd9
Thank you!

**Comment by fabianriewe** [comment]
We will add them to your content points. @mbreithecker will add them shortly!

**Comment by Lefey** [comment]
Ok, thanks for clarify

**Comment by mbreithecker** [comment]
Thanks for the submission. It's on our list for evaluation 👍 Once we have a few submissions we will start specifying the points. (I think it will take a few days)

**Comment by Lefey** [comment]
Sorry guys @fabianriewe @mbreithecker for boring you, testnet will end soon, but my content points has not changed, as you describe before. Maybe I misunderstood and points was already distributed, just want be sure you dont forget 😊

**Comment by mbreithecker** [comment]
Hey Lefey,
we have your contribution in our sheet. 
Because we need to discuss the points for each custom task individually, we do it when we have all tasks and the submission is closed (i.e. testnet ends)
So no worries, you will get your points :-)

**Pull request merged**
